### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by alexandru** [traneio/future#1]
Hello,

In benchmarks you have to be really careful about what you're measuring. For example when you’re measuring how fast you can extract a value from a `Promise` by blocking on its result, using your [get implementation](https://github.com/traneio/future/blob/master/future-java/src/main/java/io/trane/future/Promise.java#L230), what actually happens there is that your operation is going to be faster than Scala’s [Await.result](http://www.scala-lang.org/api/current/scala/concurrent/Await$.html#result[T](awaitable:scala.concurrent.Awaitable[T],atMost:scala.concurrent.duration.Duration):T) because Scala uses its [BlockContext](http://www.scala-lang.org/api/current/scala/concurrent/BlockContext.html) to signal to the underlying thread-pool that a blocking op occurs, so you have extra overhead because `Await.result` calls [blocking](http://www.scala-lang.org/api/current/scala/concurrent/index.html#blocking[T](body:=>T):T), which involves a `ThreadLocal.get` + an extra closure being created and then executed.
And if it actually runs on a `BlockingContext` enabled thread-pool (like Scala's `global`), it also means it’s going to add an extra thread to the pool.

For measuring Monix, as I've said on the channel, by calling `runAsync(Scheduler)` it gives you back a `CancelableFuture`, which for actually async results (as those created by `Task.create`) is powered by an underlying Scala `Promise`. But this is only for convenience. If you want to measure its actual performance, then you need to work with `runAsync(Callback)`.

First of all you need a callback implementation:

```scala
import monix.eval.Callback
import java.util.concurrent.locks.AbstractQueuedSynchronizer
import scala.concurrent.duration.{Duration, FiniteDuration}
import scala.util.{Failure, Success, Try}

final class AwaitableCallback[A] extends Callback[A] {
  /** Keeps track of the completion status:
    *
    *  - 0: initial value, waiting for result
    *  - 1: completed with success
    *  - 2: completed with failure
    */
  private[this] var state = 0
  private[this] var success: A = _
  private[this] var error: Throwable = _
  private[this] val latch = new OneShotLatch

  def onSuccess(value: A): Unit = {
    this.success = value
    this.state = 1
    latch.releaseShared(1)
  }

  def onError(ex: Throwable): Unit = {
    this.error = ex
    this.state = 2
    latch.releaseShared(1)
  }

  def value: Option[Try[A]] =
    state match {
      case 0 => None
      case 1 => Some(Success(success))
      case _ => Some(Failure(error))
    }

  def blockForResult: A = {
    tryAwait(Duration.Inf)
    state match {
      case 1 => success
      case _ => throw error
    }
  }

  private def tryAwait(atMost: Duration): Boolean = {
    import Duration.Undefined
    if (state != 0) true else {
      atMost match {
        case e if e eq Undefined =>
          throw new IllegalArgumentException("cannot wait for Undefined period")
        case Duration.Inf =>
          latch.acquireSharedInterruptibly(1)
        case f: FiniteDuration if f > Duration.Zero =>
          latch.tryAcquireSharedNanos(1, f.toNanos)
        case _ =>
          () // Do nothing
      }

      state != 0
    }
  }

  private final class OneShotLatch extends AbstractQueuedSynchronizer {
    override protected def tryAcquireShared(ignored: Int): Int =
      if (getState != 0) 1 else -1

    override protected def tryReleaseShared(ignore: Int): Boolean = {
      setState(1)
      true
    }
  }
}
```

We are also going to replace `Task.create` with `Task.unsafeCreate`, because `Task.create` has extra overhead for safety reasons:

```scala
def signalValue[A](value: A): Task[A] =
  Task.unsafeCreate { (context, callback) =>
    callback.onSuccess(value)
  }
```

Speaking of safety, Monix has this feature where it does execution in batches, so it executes multiple cycles on the same thread, but then it jumps threads when its internal counter goes over a threshold. The purpose is to preserve liveness and not keep a thread occupied forever. Such a jump should happen if you do enough `flatMap` calls in a loop (e.g. over 1024), but for a benchmark there's no point in having such a feature enabled:

```scala
import monix.execution.ExecutionModel.SynchronousExecution
import monix.execution.Scheduler.global

implicit val scheduler = global.withExecutionModel(SynchronousExecution)
```

And then blocking for that result:

```scala
val awaitable = new AwaitableCallback[String]
signalValue("hello").runAsync(awaitable)
val result: String = awaitable.blockForResult
```

Also as a word of warning, this never happens in actual code:

```java
for (int i = 0; i < 100; i++)
  f = f.flatMap(flatMapF);
```

What happens in actual code are recursive loops:

```scala
def loop[A](n: Int, task: Task[A]): Task[A] =
  task.flatMap { a =>
    if (n <= 0) Task.now(a)
    else loop(n-1, task)
  }
```

And yes, it does make a difference because your sample does more strict evaluation than what happens in practice.

And if you're actually interested in the performance of `flatMap`, you have to do it enough times to make sure that it dominates the throughput of the benchmark, otherwise with an efficient `flatMap` you're going to measure how fast you're blocking for a result. So instead of `100`, make that `10000` at least.

And another thought: `Task` makes it possible to describe an entire program and then call `runAsync` *only once* at the edges of that program, something that you *cannot do* with a strict Future/Promise implementation. This means that the performance of `Task.runAsync` is less relevant than the performance of its `flatMap`.

**Comment by fwbrasil** [comment]
@alexandru thanks for the feedback!

> In benchmarks you have to be really careful about what you're measuring. For example when you’re measuring how fast you can extract a value from a Promise by blocking on its result, using your get implementation, what actually happens there is that your operation is going to be faster than Scala’s Await.result because Scala uses its BlockContext to signal to the underlying thread-pool that a blocking op occurs, so you have extra overhead because Await.result calls blocking, which involves a ThreadLocal.get + an extra closure being created and then executed.
> And if it actually runs on a BlockingContext enabled thread-pool (like Scala's global), it also means it’s going to add an extra thread to the pool.

These are good points, but there isn't much that can be done to workaround them. The purpose of the benchmarks is to compare the throughput and allocation rate of the future implementations in a fair way, so it needs to take into consideration the full cycle: from creating the composition to actually returning the value. For instance, async execution models defer part of the execution overhead to a thread pool, if the benchmark doesn't wait for the final result it'll take into consideration only the overhead to enqueue the task.

Considering that all futures are always satisfied by the end of the benchmark, well-optimized implementations should be able to return the value without much overhead.

> For measuring Monix, as I've said on the channel, by calling runAsync(Scheduler) it gives you back a CancelableFuture, which for actually async results (as those created by Task.create) is powered by an underlying Scala Promise. But this is only for convenience. If you want to measure its actual performance, then you need to work with runAsync(Callback).

Would it make sense to have something like this built-in in Monix as a more lightweight way of blocking on the result? I'm not comfortable with adding the specialized callback just for the purpose of benchmarking. For instance, for the sake of fairness, if I add this callback I'd need to implement something similar for Scala futures to work around its inefficiency to return satisfied futures.

> We are also going to replace Task.create with Task.unsafeCreate, because Task.create has extra overhead for safety reasons:

Sounds good. One question, though: I'm wondering if it's fair to set the result of the task upon construction. For the other implementations, the value of the `Promise` is set only at the end of the benchmark and it implies extra overhead. If I change the call that sets the `Promise` result to immediately after its creation, most future implementations would have much better performance.

> Speaking of safety, Monix has this feature where it does execution in batches, so it executes multiple cycles on the same thread, but then it jumps threads when its internal counter goes over a threshold. The purpose is to preserve liveness and not keep a thread occupied forever. Such a jump should happen if you do enough flatMap calls in a loop (e.g. over 1024), but for a benchmark there's no point in having such a feature enabled:

The project actually has two benchmarks: one uses the sync execution model and the other one the async model. I think it's important to have results for both modes. 

> Also as a word of warning, this never happens in actual code:

It does and it's normally the common case. Most future compositions that I see are long chains of transformations (`map`, `flatMap`, etc) and not recursive. That's what this benchmark simulates.

> And if you're actually interested in the performance of flatMap, you have to do it enough times to make sure that it dominates the throughput of the benchmark, otherwise with an efficient flatMap you're going to measure how fast you're blocking for a result. So instead of 100, make that 10000 at least.

I guess the question here is more about the objective of these benchmarks. From a comparison standpoint, what matters is overall throughput including the operation to get the future result. 

> And another thought: Task makes it possible to describe an entire program and then call runAsync only once at the edges of that program, something that you cannot do with a strict Future/Promise implementation. This means that the performance of Task.runAsync is less relevant than the performance of its flatMap.

Isn't it the other way around? The overhead to create a Task should be minimal (allocation) and most of the work would be done by `runAsync`.

**Comment by fwbrasil** [comment]
@alexandru have you had some time to take a look at this? I'm inclined to remove the Monix benchmarks since I'm not sure it's a fair and correct comparison.

**Comment by fwbrasil** [comment]
@alexandru I've compiled the jmh results into a [spreadsheet](https://docs.google.com/spreadsheets/d/1_s4dFQChQbDqQIg1ci-oBM9HMmmolLJLIM_IfwSEUWU/edit?usp=sharing) in case you want to see the results for the current implementation of the Monix benchmark. Also, you can run the benchmarks using the `future-benchmark/run.sh`, it only requires maven installed.

**Comment by fwbrasil** [comment]
I've just removed the Monix benchmarks
